# Generated by Django 4.2.9 on 2026-10-03 15:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('warehouse', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockin',
            name='approved_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='审批时间'),
        ),
        migrations.AddField(
            model_name='stockin',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_stock_ins', to=settings.AUTH_USER_MODEL, verbose_name='审批人'),
        ),
        migrations.AddField(
            model_name='stockin',
            name='risk_level',
            field=models.CharField(choices=[('normal', '普通'), ('high', '高风险')], default='normal', max_length=20, verbose_name='风险等级'),
        ),
        migrations.AddField(
            model_name='stockin',
            name='status',
            field=models.CharField(choices=[('pending', '待审批'), ('approved', '已通过'), ('rejected', '已拒绝')], default='approved', max_length=20, verbose_name='审批状态'),
        ),
    ]
