# Generated by Django 4.2.9 on 2026-10-03 15:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DutyConflictRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='规则名称')),
                ('description', models.CharField(blank=True, max_length=200, verbose_name='规则说明')),
                ('rule_type', models.CharField(choices=[('role_combo', '角色权限组合冲突'), ('self_approval', '创建人自审冲突')], max_length=20, verbose_name='规则类型')),
                ('permission_a', models.CharField(blank=True, max_length=50, verbose_name='冲突权限A')),
                ('permission_b', models.CharField(blank=True, max_length=50, verbose_name='冲突权限B')),
                ('object_type', models.CharField(blank=True, choices=[('stock_in', '收件（入库）')], max_length=20, verbose_name='业务对象类型')),
                ('severity', models.CharField(choices=[('high', '高'), ('medium', '中'), ('low', '低')], default='medium', max_length=10, verbose_name='严重级别')),
                ('status', models.CharField(choices=[('draft', '草稿'), ('published', '已发布'), ('disabled', '已停用')], default='draft', max_length=10, verbose_name='状态')),
                ('published_at', models.DateTimeField(blank=True, null=True, verbose_name='发布时间')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_duty_rules', to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
                ('published_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='published_duty_rules', to=settings.AUTH_USER_MODEL, verbose_name='发布人')),
            ],
            options={
                'verbose_name': '职责冲突规则',
                'verbose_name_plural': '职责冲突规则',
                'db_table': 'sod_duty_conflict_rule',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DutyExemption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(max_length=200, verbose_name='豁免依据')),
                ('expires_at', models.DateTimeField(verbose_name='失效时间')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否启用')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_duty_exemptions', to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
                ('rule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exemptions', to='sod.dutyconflictrule', verbose_name='豁免规则')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='duty_exemptions', to=settings.AUTH_USER_MODEL, verbose_name='豁免用户')),
            ],
            options={
                'verbose_name': '紧急豁免',
                'verbose_name_plural': '紧急豁免',
                'db_table': 'sod_duty_exemption',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DutyDelegation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('permission', models.CharField(max_length=50, verbose_name='代理权限')),
                ('reason', models.CharField(max_length=200, verbose_name='代理依据')),
                ('start_at', models.DateTimeField(verbose_name='生效时间')),
                ('end_at', models.DateTimeField(verbose_name='失效时间')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否启用')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
                ('delegate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_duty_delegations', to=settings.AUTH_USER_MODEL, verbose_name='代理人')),
                ('delegator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='given_duty_delegations', to=settings.AUTH_USER_MODEL, verbose_name='委托人')),
            ],
            options={
                'verbose_name': '临时代理',
                'verbose_name_plural': '临时代理',
                'db_table': 'sod_duty_delegation',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DutyCheckLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('check_type', models.CharField(choices=[('role_combo', '角色权限组合'), ('self_approval', '创建人自审'), ('delegation', '临时代理')], max_length=20, verbose_name='判断类型')),
                ('object_type', models.CharField(blank=True, max_length=50, verbose_name='业务对象类型')),
                ('object_id', models.BigIntegerField(blank=True, null=True, verbose_name='业务对象ID')),
                ('decision', models.CharField(choices=[('blocked', '已阻止'), ('allowed_exempted', '豁免放行'), ('bypassed', '超级管理员绕过')], max_length=20, verbose_name='判断结果')),
                ('basis', models.TextField(blank=True, verbose_name='判断依据')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='判断时间')),
                ('exemption', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='sod.dutyexemption', verbose_name='使用豁免')),
                ('rule', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='sod.dutyconflictrule', verbose_name='命中规则')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='被判断用户')),
            ],
            options={
                'verbose_name': '职责冲突判断日志',
                'verbose_name_plural': '职责冲突判断日志',
                'db_table': 'sod_duty_check_log',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DutyConflictRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sources', models.JSONField(default=list, verbose_name='冲突来源')),
                ('status', models.CharField(choices=[('open', '待处理'), ('exempted', '已豁免'), ('resolved', '已解决')], default='open', max_length=10, verbose_name='状态')),
                ('first_seen_at', models.DateTimeField(auto_now_add=True, verbose_name='首次发现时间')),
                ('last_seen_at', models.DateTimeField(auto_now=True, verbose_name='最近发现时间')),
                ('resolved_at', models.DateTimeField(blank=True, null=True, verbose_name='处理时间')),
                ('resolution_note', models.CharField(blank=True, max_length=200, verbose_name='处理说明')),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='处理人')),
                ('rule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conflict_records', to='sod.dutyconflictrule', verbose_name='冲突规则')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='duty_conflict_records', to=settings.AUTH_USER_MODEL, verbose_name='冲突用户')),
            ],
            options={
                'verbose_name': '职责冲突记录',
                'verbose_name_plural': '职责冲突记录',
                'db_table': 'sod_duty_conflict_record',
                'ordering': ['-last_seen_at'],
                'unique_together': {('rule', 'user')},
            },
        ),
    ]
