# Generated by Django 4.2.9 on 2026-10-03 15:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DutyConflictRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='规则名称')),
                ('rule_type', models.CharField(choices=[('role_combo', '权限组合冲突'), ('self_approval', '自审冲突')], max_length=20, verbose_name='规则类型')),
                ('permissions', models.JSONField(blank=True, default=list, verbose_name='冲突权限集合')),
                ('object_type', models.CharField(blank=True, max_length=50, verbose_name='业务对象类型')),
                ('action', models.CharField(blank=True, max_length=100, verbose_name='受控动作')),
                ('creator_path', models.CharField(blank=True, max_length=200, verbose_name='创建人定位路径')),
                ('severity', models.CharField(choices=[('high', '高'), ('medium', '中'), ('low', '低')], default='medium', max_length=10, verbose_name='严重级别')),
                ('description', models.TextField(blank=True, verbose_name='规则说明')),
                ('status', models.CharField(choices=[('draft', '草稿'), ('published', '已发布'), ('disabled', '已停用')], default='draft', max_length=20, verbose_name='状态')),
                ('publish_impact', models.JSONField(blank=True, default=dict, verbose_name='发布影响快照')),
                ('published_at', models.DateTimeField(blank=True, null=True, verbose_name='发布时间')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_sod_rules', to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
                ('published_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='published_sod_rules', to=settings.AUTH_USER_MODEL, verbose_name='发布人')),
            ],
            options={
                'verbose_name': '职责冲突规则',
                'verbose_name_plural': '职责冲突规则',
                'db_table': 'sod_duty_conflict_rule',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='EmergencyExemption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.TextField(verbose_name='豁免依据')),
                ('start_at', models.DateTimeField(verbose_name='生效时间')),
                ('end_at', models.DateTimeField(verbose_name='失效时间')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否有效')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('approved_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_exemptions', to=settings.AUTH_USER_MODEL, verbose_name='批准人')),
                ('rule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exemptions', to='sod.dutyconflictrule', verbose_name='豁免规则')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sod_exemptions', to=settings.AUTH_USER_MODEL, verbose_name='豁免用户')),
            ],
            options={
                'verbose_name': '紧急豁免',
                'verbose_name_plural': '紧急豁免',
                'db_table': 'sod_emergency_exemption',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Delegation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('permissions', models.JSONField(default=list, verbose_name='代理权限集合')),
                ('reason', models.TextField(verbose_name='代理依据')),
                ('start_at', models.DateTimeField(verbose_name='生效时间')),
                ('end_at', models.DateTimeField(verbose_name='失效时间')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否有效')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_delegations', to=settings.AUTH_USER_MODEL, verbose_name='登记人')),
                ('delegate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='delegations_received', to=settings.AUTH_USER_MODEL, verbose_name='代理人')),
                ('delegator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='delegations_given', to=settings.AUTH_USER_MODEL, verbose_name='委托人')),
            ],
            options={
                'verbose_name': '临时代理',
                'verbose_name_plural': '临时代理',
                'db_table': 'sod_delegation',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ConflictCheckRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=100, verbose_name='尝试动作')),
                ('object_type', models.CharField(blank=True, max_length=50, verbose_name='业务对象类型')),
                ('object_id', models.IntegerField(blank=True, null=True, verbose_name='业务对象ID')),
                ('object_label', models.CharField(blank=True, max_length=200, verbose_name='业务对象描述')),
                ('result', models.CharField(choices=[('blocked', '已阻止'), ('exempted', '豁免放行')], max_length=20, verbose_name='判定结果')),
                ('basis', models.JSONField(default=dict, verbose_name='判定依据')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='判定时间')),
                ('rule', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='check_records', to='sod.dutyconflictrule', verbose_name='命中规则')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sod_check_records', to=settings.AUTH_USER_MODEL, verbose_name='操作用户')),
            ],
            options={
                'verbose_name': '冲突判定记录',
                'verbose_name_plural': '冲突判定记录',
                'db_table': 'sod_conflict_check_record',
                'ordering': ['-created_at'],
            },
        ),
    ]
